logLevel: info
logDestinations: [stdout]

api: yes
apiAddress: :9997

rtsp: yes
rtspAddress: :8554
protocols: [tcp, udp]

hls: yes
hlsAddress: :8888
hlsAlwaysRemux: yes
hlsSegmentCount: 7
hlsSegmentDuration: 1s

webrtc: yes
webrtcAddress: :8889

playback: yes
playbackAddress: :9996

pathDefaults:
  record: yes
  recordPath: /recordings/%path/%Y-%m-%d_%H-%M-%S-%f
  recordFormat: fmp4
  recordDeleteAfter: 168h

paths:
  all_others:
    source: publisher
